### PR TITLE
Sage McGill

### PR DESCRIPTION
**Pull request by sagekieran**

### CODE REVIEW

**Comment by YSavir** [comment]
Hi Sage!

It looks like you have a file named 'favorite-foods' in the root of the repository. Can you remove it? Once it's gone I can accept your pull request.

**Comment by sagekieran** [comment]
favorite-foods deleted

**Comment by YSavir** [comment]
Hmm. Looks like the _contents_ of favorite-foods has been cleared out, but it looks like the file itself is still there.

**Comment by sagekieran** [comment]
Okay,  hopefully I've done it correctly this time.

**Pull request merged**
